spring:
  application:
    name: imechanic

  # MYSQL DRIVE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url:
    username:
    password:


logging:
  level:
    web: warn


# SECURITY CONFIGURATION
auth:
  secret:
    # https://randomkeygen.com/hmac-key
    key:
  issuer:
