spring:
  application:
    name: imechanic

  # MYSQL DRIVE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:mysql://localhost:3306/imechanic_db
    username:
    password:

  # JAVA EMAIL CONFIGURATION
  mail:
    password:
    username:

# SECURITY CONFIGURATION
auth:
  secret:
    # https://randomkeygen.com/hmac-key
    key:

  # MEDIA UPLOAD CONFIGURATION
cloudinary:
  url:

logging:
  level:
    web: warn