spring:
  application:
    name: imechanic

  # MYSQL DRIVE CONFIGURATION
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/imechanic_db
    username: 
    password: 

  # JAVA EMAIL CONFIGURATION
  mail:
    password: 
    username: foodhub.recetas.xxx@gmail.com

# SECURITY CONFIGURATION
auth:
  secret:
    # https://randomkeygen.com/hmac-key
    key: 

  allowed-origin: http://localhost:5173

  # COOKIES CONFIGURATION
  cookie:
    secure: false
    same-site: Lax

  # MEDIA UPLOAD CONFIGURATION
cloudinary:
  url: cloudinary://<000000000000000>:<XYZXYZXYZYXZYXYZ>

logging:
  level:
    root: info
    com.backend.imechanic: debug